# Timestep-to-timestep

What happens when the model actually runs? To really understand the model, we have to understand its steps and the logic and implications of each one.

Each model run is composed of several timesteps, and during each step events like death, birth, immigration, and speciation happen to individuals or species in the model.

These events happen randomly based on the model parameters, causing the state of the local and meta communities to change as the model is run.

## Deaths

Every timestep, no matter what, an individual in the local community dies.

If we are using a neutral model (parameter neut_delta = 1), a completely random individual is always chosen for death. This is the definition of neutral evolution!

But if the model is not neutral, an individual's chance of death (or ability to survive in its environment) is based on its ability to compete with other individuals and survive in its environment.

The closer the trait of the individual is to the environmental optimum of 1, a perfect match to its environment, the more likely it is to survive.

But at the same time, the more individuals that have similar traits to it, the more the resources each needs will overlap, and this competition will make it harder to survive. (Add more on theory here).

An outcome of RoLE's individual-based model framework is that intraspecific competition is modeled, and even emphasized. Since individuals of the same species typically have similar traits, they will compete more. (could add info on what comp and env sigma do, but this info might belong in parameters section).

## Birth and dispersal

Every timestep, no matter what, EITHER birth or dispersal causes a new individual to appear in the local community.

Birth is when an individual in the local community reproduces to make a single offspring.

Dispersal is when an individual is born in the metacommunity and immigrates from the metacommunity to the local community.

The chance of each is based on the dispersal_prob param, which is simply the chance of dispersal (making 1-dispersal_prob the chance of birth).

## Speciation

Speciation in RoLE works by making the individual that was just birthed or immigrated a new species.

Speciation may or may not happen each timestep, with a chance equal to speciation_local.

Realistically speciation_local is an extremely small value like 0.001 to capture the rarity of speciation events over time.

When speciation happens, a new tip is added to the phylogeny for the new species.

## Trait change

When birth, dispersal, or speciation happens, the new individual gets a new trait deviating from the traits of its parent.

This deviation depends on the trait_sigma parameter - the larger the trait_sigma the more child traits will deviate from parent traits. (this is also based on speciation meta and extinction meta, which could be worth explaining)
